// swift-tools-version:5.9
// Generated by SwiftFlowKit

import PackageDescription

let package = Package(
    name: "XCResultKit",
    platforms: [
        .macOS("14.0"),
    ],
    products: [
        .library(
            name: "XCResultKit",
            targets: ["XCResultKit"]
        ),
        .executable(
            name: "XCResultKitExecutable",
            targets: ["XCResultKitExecutable"]
        ),
    ],
    dependencies: [
        .package(url: "https://github.com/JohnSundell/Files", from: "4.2.0"),
        .package(url: "https://github.com/kareman/SwiftShell", from: "5.1.0"),
        .package(url: "https://github.com/apple/swift-argument-parser.git", from: "0.3.0"),
        .package(url: "https://github.com/nikolainobadi/NnConfigGenKit.git", branch: "main"),
    ],
    targets: [
        .target(
            name: "XCResultKit",
            dependencies: [
                "Files",
                "SwiftShell",
                "NnConfigGenKit",
                .product(name: "ArgumentParser", package: "swift-argument-parser"),
            ]
        ),
        .executableTarget(
            name: "XCResultKitExecutable",
            dependencies: ["XCResultKit"]
        ),
    ]
)
