// swift-tools-version:5.9
// Generated by SwiftFlowKit

import PackageDescription

let package = Package(
    name: "XCResultKit",
    platforms: [
        .macOS("14.0"),
    ],
    products: [
        .library(
            name: "XCResultKit",
            targets: ["XCResultKit"]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/kareman/SwiftShell", from: "5.1.0"),
        .package(url: "https://github.com/nikolainobadi/NnTestKit", branch: "main")
    ],
    targets: [
        .target(
            name: "XCResultKit",
            dependencies: [
                "SwiftShell"
            ]
        ),
        .testTarget(
            name: "XCResultTests",
            dependencies: [
                "XCResultKit",
                .product(name: "NnTestHelpers", package: "NnTestKit")
            ],
            resources: [
                .copy("Resources")
            ]
        )
    ]
)
